apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-app
  labels:
    name: dev-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dev-app
  minReadySeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: dev-app
    spec:
      containers:
      - name: test
        image: gcr.io/cloudorbit/app/dev/jenkinsapp:latest
        imagePullPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: dev-app
spec:
  selector:
    name: dev-app
  ports:
    - name: port1
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dev-app
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dev-app
  targetCPUUtilizationPercentage: 80
